#!/usr/bin/env bash

# redis-server
# author: Seong Yong-ju <sei40kr@gmail.com>

basepath="$(dirname "$(realpath "$0")")"

docker run --rm \
       -v "${basepath}/conf/redis.conf:/usr/local/etc/redis/redis.conf" \
       --name redis-server \
       --sysctl net.core.somaxconn=511 \
       redis /usr/local/etc/redis/redis.conf
